modLoader = "javafml"
loaderVersion = "[33,)"
displayURL = "${modUrl}"
logoFile = "logo.png"
authors = "${modAuthor}"
license = "MIT"

[[mods]]
modId = "${modId}"
displayName = "${modName}"
version = "${minecraftVersion}-${modVersion}"
description = "${modDescription}"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "CLIENT"
