modLoader="javafml"
loaderVersion="[38,)"
displayURL="https://minecraft.curseforge.com/projects/shoulder-surfing-reloaded"
logoFile="logo.png"
authors="Sabar, Exopandora"
license="MIT"

[[mods]]
modId="shouldersurfing"
displayName="Shoulder Surfing"
version="1.18.2-${version}"
description="Shoulder Surfing Reloaded is a highly configurable third person camera mod for minecraft, originally made by Sabar."

[[dependencies.shouldersurfing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="CLIENT"
