modLoader = "javafml"
loaderVersion = "[33,)"
license = "MIT"

[[mods]]
modId = "${modId}"
version = "${minecraftVersion}-${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
credits = "${modContributors}"
description = "${modDescription}"
logoFile = "logo.png"
displayURL = "${modUrl}"

[modproperties.${modId}]
incompatibleMods = ["betterthirdperson", "nimble", "valkyrienskies"]

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "CLIENT"
