modLoader="javafml"
loaderVersion="[31,)"
displayURL="https://minecraft.curseforge.com/projects/shoulder-surfing-reloaded"
logoFile="logo.png"
authors="Sabar, Exopandora (1.7.10+)"

[[mods]]
modId="shouldersurfing"
displayName="Shoulder Surfing"
version="1.15.2-1.22"
description='''
Changes the vanilla third person camera to an over-the-shoulder camera, as made popular by Capcom's "Resident Evil 4".
Includes keybindings for adjusting the camera, along with various settings in the config file.
Code injection may fail if using mods that mess with the base files.
'''

[[dependencies.shouldersurfing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"