[versions]
minecraft = "1.18.2"
forge = "1.18.2-40.1.68"
fabric-loader = "0.14.8"
fabric-api = "0.47.7+1.18.2"
mixin = "0.8.5"
forgeconfigapiport = "3.2.3"
wthit-common = "mojmap-4.13.2"
wthit-forge = "forge-4.13.2"
wthit-fabric = "fabric-4.13.2"
badpackets-forge = "forge-0.1.2"
badpackets-fabric = "fabric-0.1.2"
night-config = "3.6.3"
create-common = "1.18.2-0.5.1.f" # forge artifact

[libraries]
minecraft-forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
forgeconfigapiport-common = { module = "net.minecraftforge:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
forgeconfigapiport-fabric = { module = "net.minecraftforge:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
wthit-common = { module = "mcp.mobius.waila:wthit-api", version.ref = "wthit-common" }
wthit-forge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-forge" }
wthit-fabric = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-fabric" }
badpackets-forge = { module = "lol.bai:badpackets", version.ref = "badpackets-forge" }
badpackets-fabric = { module = "lol.bai:badpackets", version.ref = "badpackets-fabric" }
create-common = { module = "maven.modrinth:create", version.ref = "create-common" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "night-config" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "night-config" }

[plugins]
modpublishplugin = { id = "me.modmuss50.mod-publish-plugin", version = "0.6.3" }
vanillagradle = { id = "org.spongepowered.gradle.vanilla", version = "0.2.1-SNAPSHOT" }
forgegradle = { id = "net.minecraftforge.gradle", version = "[6.0.16,6.2)" }
fabricloom = { id = "fabric-loom", version = "1.4.+" }
mixingradle = { id = "org.spongepowered.mixin", version = "0.7.+" }
