[versions]
minecraft = "1.21.10"
forge = "1.21.10-60.0.0"
neoforge = "21.10.0-beta"
neoform = "1.21.10-20251007.142004"
fabric-loader = "0.17.2"
fabric-api = "0.134.1+1.21.10"
mixin = "0.8.7"
forgeconfigapiport = "21.10.0"
wthit-common = "mojmap-17.0.4"
wthit-forge = "forge-17.0.4"
wthit-neoforge = "neo-17.0.4"
wthit-fabric = "fabric-17.0.4"
jade-common = "7056468" # 1.21.10-20.0.5-neoforge
jade-forge = "7056468" # 1.21.10-20.0.5-neoforge, temporarily use common artifact for compilation
jade-neoforge = "7056468" # 1.21.10-20.0.5-neoforge
jade-fabric = "7056475" # 1.21.10-20.0.5-fabric
badpackets-forge = "forge-0.10.2"
badpackets-neoforge = "neo-0.10.2"
badpackets-fabric = "fabric-0.10.2"
curios = "11.0.1+1.21.5"

[libraries]
minecraft-forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
minecraft-neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
forgeconfigapiport-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapiport" }
forgeconfigapiport-fabric = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
forgeconfigapiport-forge = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-forge", version.ref = "forgeconfigapiport" }
wthit-common = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-common" }
wthit-forge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-forge" }
wthit-neoforge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-neoforge" }
wthit-fabric = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-fabric" }
jade-common = { module = "curse.maven:jade-324717", version.ref = "jade-common" }
jade-forge = { module = "curse.maven:jade-324717", version.ref = "jade-forge" }
jade-neoforge = { module = "curse.maven:jade-324717", version.ref = "jade-neoforge" }
jade-fabric = { module = "curse.maven:jade-324717", version.ref = "jade-fabric" }
badpackets-forge = { module = "lol.bai:badpackets", version.ref = "badpackets-forge" }
badpackets-neoforge = { module = "lol.bai:badpackets", version.ref = "badpackets-neoforge" }
badpackets-fabric = { module = "lol.bai:badpackets", version.ref = "badpackets-fabric" }
curios-neoforge = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
eventbus-validator = { module = "net.minecraftforge:eventbus-validator", version = "7.0-beta.12" }

[plugins]
modpublishplugin = { id = "me.modmuss50.mod-publish-plugin", version = "1.0.0" }
forgegradle = { id = "net.minecraftforge.gradle", version = "[6.0.36,6.2)" }
fabricloom = { id = "fabric-loom", version = "1.11-SNAPSHOT" }
moddevgradle = { id = "net.neoforged.moddev", version = "2.0.113" }
mixingradle = { id = "org.spongepowered.mixin", version = "0.7.+" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.2" }
