name: Bug Report
description: Create a bug report to help improve Shoulder Surfing
title: "Short description of the bug"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure you have read the [FAQ](https://github.com/Exopandora/ShoulderSurfing#faq) section before submitting a new issue.
        Please open an incompatibility issue when the bug is not present without any other mods installed.
        In order to find the conflicting mod, you can use the method described [here](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug
      placeholder: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Game Logs
      description: |
        Navigate to `.minecraft/logs/` and upload the file named `latest.log` to https://mclo.gs/ and paste the link here.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other information about the problem.
    validations:
      required: false
