modLoader = "javafml"
loaderVersion = "[2,)"
displayURL = "https://minecraft.curseforge.com/projects/shoulder-surfing-reloaded"
logoFile = "logo.png"
authors = "Exopandora"
license = "MIT"

[[mixins]]
config = "shouldersurfing.common.mixins.json"

[[mixins]]
config = "shouldersurfing.neoforge.mixins.json"

[[mixins]]
config = "shouldersurfing.compat.oculus.mixins.json"

[[mods]]
modId = "shouldersurfing"
displayName = "Shoulder Surfing"
version = "1.20.4-${version}"
description = "Shoulder Surfing Reloaded is a highly configurable third person camera mod for minecraft, originally made by Sabar."

[[dependencies.shouldersurfing]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.shouldersurfing]]
modId = "forgeconfigapiport"
type = "required"
versionRange = "[20.4.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.shouldersurfing]]
modId = "betterthirdperson"
type = "incompatible"
side = "CLIENT"

[[dependencies.shouldersurfing]]
modId = "cameraoverhaul"
type = "incompatible"
side = "CLIENT"

[[dependencies.shouldersurfing]]
modId = "nimble"
type = "incompatible"
side = "CLIENT"
